### ISSUE TITLE
Instruction number is different from verilator when we run Nutshell(OSCPU/NutShell).

### ISSUE THREAD

**Issue by zhaoxueyan1** [ucsc-vama/essent#3]

**Comment by sbeamer** [comment]
More information could help us look into this.

I'm not familiar with OSCPU/NutShell, but if it uses riscv-fesvr (with pthreads) like Rocket Chip, the non-determinism of those two threads interacting (riscv-fesvr & simulation) can change the number of cycles the simulation runs, but that probably shouldn't change the instruction count.

**Comment by sbeamer** [comment]
Without more information, I'm not sure how to help debug. I'm going to close this to tidy things, but please reopen it or make a new issue if there is a specific thing we can help with.
