### ISSUE TITLE
Any plan for multi-threading?

### ISSUE THREAD

**Issue by sashimi-yzh** [ucsc-vama/essent#5]
`verilator` supports generating multi-threading C++ models by giving `-thread` option. Servers can benefit a lot from multi-threading. Is there any plan to support generating multi-threading C++ code?

**Comment by sbeamer** [comment]
Yes, but this is long-term research and will unfortunately not be available for some time.

**Comment by sashimi-yzh** [comment]
I see.

Thanks for such great project! :)

**Comment by davidmlw** [comment]
Excellent work! 
Maybe another speedup requirement is compilation time. How about split the .h file into several .cc files, so the compilation can be speedup by `make -j`. Compilation time is also another important factor for fast turnaround
